
console.log("      ================================       ")
console.log("             MEU APLICATIVO                  ")
console.log("      ================================       ")
console.log("Nome: Davi. L                                 ")
console.log("Cidade: Schroeder - SC                        ")
console.log("Atividade de interesse: jogos, Filmes         ")
console.log("Quero aprender: desenvolvimento de aplicativos")
console.log("Área de interesse: tecnologia                 ")
console.log("Mensagem: Estou evoluindo na programação!     ")
console.log("Meu próximo desafio: criar meu primeiro jogo. ")